language: node_js
node_js:
  - 0.10


env: DB=couchdb

before_script:
  - curl -X PUT localhost:5984/kanso-example-app
  - npm install kanso -g

script: "kanso install; kanso push http://localhost:5984/kanso-example-app"
