language: node_js
node_js:
  - 0.10

install:
  - npm install -g tap kanso

env: DB=couchdb

before_script:
  - curl -X PUT localhost:5984/kanso-example-app

script: "kanso install; kanso push http://localhost:5984/kanso-example-app; tap test"
